apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-rota-api
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: rota-api-csharp
  duration: "30s"
